# Generated by Django 3.2.18 on 2023-05-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default=None, max_length=100, null=True)),
                ('states', models.CharField(max_length=100, null=True)),
                ('positive', models.CharField(max_length=100, null=True)),
                ('negative', models.CharField(max_length=100, null=True)),
                ('pending', models.CharField(max_length=100, null=True)),
                ('hospitalizedCurrently', models.CharField(max_length=100, null=True)),
                ('hospitalizedCumulative', models.CharField(max_length=100, null=True)),
                ('inIcuCurrently', models.CharField(max_length=100, null=True)),
                ('inIcuCumulative', models.CharField(max_length=100, null=True)),
                ('onVentilatorCurrently', models.CharField(max_length=100, null=True)),
                ('onVentilatorCumulative', models.CharField(max_length=100, null=True)),
                ('dateChecked', models.DateTimeField()),
                ('death', models.CharField(max_length=100, null=True)),
                ('hospitalized', models.CharField(max_length=100, null=True)),
                ('totalTestResults', models.CharField(max_length=100, null=True)),
                ('lastModified', models.DateTimeField()),
                ('recovered', models.CharField(max_length=100, null=True)),
                ('total', models.IntegerField()),
                ('posNeg', models.IntegerField()),
                ('deathIncrease', models.CharField(max_length=100, null=True)),
                ('hospitalizedIncrease', models.CharField(max_length=100, null=True)),
                ('negativeIncrease', models.CharField(max_length=100, null=True)),
                ('positiveIncrease', models.CharField(max_length=100, null=True)),
                ('totalTestResultsIncrease', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
